name: Lint and Update README

on:
  push:
    branches:
      - master
    paths:
      - 'markdown/*.md'

jobs:
  lint-md:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install lint-md/cli
        run: npm install -g @lint-md/cli

      - name: Run lint-md
        run: lint-md 'markdown/*.md' --fix

  update-readme:
    needs: lint-md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate README
        run: python generate_readme.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if git commit -m "Update README after linting Markdown files"; then
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}